### ISSUE TITLE
조회 @Transaction

### ISSUE THREAD

**Issue by binary-ho** [ghdeo/hicc-toy#1]
조회 @Transaction에는 readonly 속성을 적용해야해요.
readonly 속성은 어떤 역할을 하고
적용하는 경우와 적용하지 않는 경우는 어떻게 다를까요?

**Comment by ghdeo** [comment]
readOnly 속성을 통해 예상치 못한 엔티티의 등록, 변경, 삭제를 예방할 수 있습니다.
또한 readOnly속성을 이용하면 읽기 전용이므로 영속성 컨텍스트는 스냅샷을 보관하지 않아 메모리 사용량을 최적화 할 수 있습니다.
ArticleService, CommentService, ScheduleService에 해당사항 반영하여 수정하였습니다.
