### ISSUE TITLE
rental 물품 추상화

### ISSUE THREAD

**Issue by binary-ho** [ghdeo/hicc-toy#2]
rental 물품들은 공통적으로 id, RentalStatus, Member 정보를 가지고 있습니다.
하지만 서로 같은 패키지 안에 있을 뿐 추상화 되어있지 않습니다.

만약 rental 정책이 바뀐다면 모든 물품 클래스를 일일히 수정해줘야 합니다.
어떻게 해결할 수 있을까요?

**Comment by ghdeo** [comment]
서비스 규모가 크지 않고 단순하기에 SINGLE_TABLE 전략으로 상속관계를 나타낼 수 있습니다.
Locker와 Umbrella를 Item class로 추상화 하여 해결하였습니다.
