### ISSUE TITLE
@RestController

### ISSUE THREAD

**Issue by binary-ho** [ghdeo/hicc-toy#3]
현재 컨드롤러들은 @RestController가 붙어 있습니다.
왜 @Controller 대신 @RestController를 사용했나요?
둘은 어떤 차이가 있을까요?

현재 @RestController가 붙은 컨트롤러들 안에 @RequestBody를 사용중입니다.
@RequestBody는 어떤 역할을 해주는 어노테이션인가요?

**Comment by ghdeo** [comment]
@RestController는 @Controller의 차이는 HTTP Response Body의 생성 방식에 있습니다. @Controller는 주로 View를 반환하기 위해 사용되는데 Data를 반환하기 위해서는 @ResponseBody 어노테이션을 사용해 주어야합니다. 현재 컨트롤러들은 데이터를 반환할 목적으로 작성되어 @Controller에 @ResponseBody가 추가된 @RestController를 사용하였습니다.

@RequestBody는 클라이언트에서 보낸 HTTP 요청 본문에 담긴 값들을 MessageConverter를 통해 자바 객체로의 변환과정을 처리할 필요가 있을 때 사용합니다. 
@RequestBody가 사용된 메서드들은 사용자로부터 전송된 데이터들을 객체로 처리하기위해 작성되었습니다.
