### ISSUE TITLE
ArticleService 통해서 Article 저장시 DataIntegrityViolationException 발생

### ISSUE THREAD

**Issue by ghdeo** [ghdeo/hicc-toy#6]
직접 ArticleRepository를 통해서 Article을 parameter로 넘겨주면 정상적으로 저장.
ArticleService를 통해서 ArticleRequestDto를 save의 parameter로 넘기는 방식으로 시도시 error 발생.

**Comment by ghdeo** [comment]
Article entity의 column 중 deleteYn이 ArticleRequestDto에는 없음을 확인.
Article entity의 column 중 deleteYn은 not null인 점에서 문제 발생. @ColumnDefault("'N'") 으로 지정되어 있어 값이 안넘어와도 괜찮을 줄 알았음.
ArticleRequestDto에 deleteYn을 추가하면 save 과정에서의 error는 해소되나 ArticleRequestDto에 deleteYn을 추가하지 않는 방법 모색필요.

**Comment by binary-ho** [comment]
제 생각엔 @ColumnDefault의 기능에 대한 오해가 있는거 같아요.
아래 래퍼런스를 한번 읽어 보시겠어요? 

래퍼런스 :  https://eocoding.tistory.com/71

1. 엔티티의 기본 값을 설정하는 방법 중 다른 방법을 한번 생각해볼까요?
2. 삭제 여부를 필드로 나타낸 이유가 있을까요?
3. 삭제 여부를 boolean type이 아닌, char로 설정한 이유가 있을까요?

**Comment by ghdeo** [comment]
삭제 타입을 char로 나타냈을 때 값이 전달되지 않았을 때 DataIntegrityViolationException이 발생한 것으로 보입니다.
타입을 boolean으로 변경하고 나니 기본값이 false인 터라 에러가 발생하지 않아 문제를 해결하였습니다.
